#! /usr/bin/env node

const fs = require('fs');
const { exec } = require('child_process');
const path = require('path');

const packageJsonPath = path.join(process.cwd(), 'package.json');
const androidGradlePath = path.join(process.cwd(), 'android/app/build.gradle')

const packageObject = require(packageJsonPath);

const version = packageObject.version.split('.').map(num => parseInt(num));

version[2] += 1;
const newVersion = version.join('.');

const androidScript = fs.readFileSync(androidGradlePath)
const newAndroidScript = androidScript.replace(/versionName .+"?'?$/, `version Name "${newVersion}"`);

fs.writeFileSync(androidGradlePath, newAndroidScript)
packageObject.version = newVersion;

fs.writeFileSync(packageJsonPath, JSON.stringify(packageObject, null, 2));
console.log(`Current version: ${newVersion}`);