#! /usr/bin/env node

const fs = require('fs');
const { exec } = require('child_process');
const path = require('path');

const packageJsonPath = path.join(process.cwd(), 'package.json');
const packageObject = require(packageJsonPath);

const version = packageObject.version.split('.').map(num => parseInt(num));

version[2] += 1;
const newVersion = version.join('.');
const command = `npx capacitor-set-version -v ${newVersion} -b 1`
exec(command, (error, stdout, stderr) => {
    if (error) {
        console.error(`Unable to exec ${error}`);
        return;
    }
    if (stderr) {
        console.error(`${stderr}`);
        return;
    }
});
packageObject.version = newVersion;

fs.writeFileSync(packageJsonPath, JSON.stringify(packageObject, null, 2));
console.log(`Current version: ${newVersion}`);